export default [
  {
    "_id": "A101",
    "title": "Propulsion Assignment",
    "course": "RS101",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-08T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A102",
    "title": "Combustion Analysis",
    "course": "RS101",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-08T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A103",
    "title": "Nozzle Design Project",
    "course": "RS101",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-08T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A201",
    "title": "Aerodynamics Quiz",
    "course": "RS102",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-10T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A202",
    "title": "Flow Analysis",
    "course": "RS102",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-10T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A203",
    "title": "Heating Analysis",
    "course": "RS102",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-10T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A301",
    "title": "Structural Design Task",
    "course": "RS103",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-13T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A302",
    "title": "Orbital Calculations",
    "course": "RS103",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-13T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A303",
    "title": "Systems Engineering Exam",
    "course": "RS103",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "due_date": "2025-09-13T23:59:00",
    "available_date": "2025-09-01T00:00:00"
  },
  {
    "_id": "A10401",
    "title": "Mechanisms Problem Set",
    "course": "RS104",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-06T23:59:00"
  },
  {
    "_id": "A10402",
    "title": "Spectroscopy Report",
    "course": "RS104",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-06T23:59:00"
  },
  {
    "_id": "A10403",
    "title": "Stereochemistry Quiz",
    "course": "RS104",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-06T23:59:00"
  },
  {
    "_id": "A10501",
    "title": "Coordination Chemistry Assignment",
    "course": "RS105",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-15T23:59:00"
  },
  {
    "_id": "A10502",
    "title": "Organometallic Catalysis Report",
    "course": "RS105",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-15T23:59:00"
  },
  {
    "_id": "A10503",
    "title": "Bioinorganic Case Study",
    "course": "RS105",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-15T23:59:00"
  },
  {
    "_id": "A10601",
    "title": "Thermodynamics Problem Set",
    "course": "RS106",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-19T23:59:00"
  },
  {
    "_id": "A10602",
    "title": "Kinetics Data Analysis",
    "course": "RS106",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-19T23:59:00"
  },
  {
    "_id": "A10603",
    "title": "Quantum Chemistry Exercise",
    "course": "RS106",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-19T23:59:00"
  },
  {
    "_id": "A10701",
    "title": "Tengwar Transcription Exercise",
    "course": "RS107",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-07T23:59:00"
  },
  {
    "_id": "A10702",
    "title": "Quenya Morphology Quiz",
    "course": "RS107",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-07T23:59:00"
  },
  {
    "_id": "A10703",
    "title": "Sindarin Translation Assignment",
    "course": "RS107",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-07T23:59:00"
  },
  {
    "_id": "A10801",
    "title": "Cultural Protocol Brief",
    "course": "RS108",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-11T23:59:00"
  },
  {
    "_id": "A10802",
    "title": "Treaty Draft Project",
    "course": "RS108",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-11T23:59:00"
  },
  {
    "_id": "A10803",
    "title": "Negotiation Strategy Analysis",
    "course": "RS108",
    "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus maiores atque odit quos optio praesentium voluptatibus recusandae! Mollitia facilis blanditiis aut quis voluptas debitis atque repellendus, fugiat iste officiis. \n Quos eius beatae quisquam obcaecati, laborum temporibus, cumque architecto ea a veritatis dolorem delectus quibusdam, dignissimos ex. Rerum accusantium dolorum quia, quidem eligendi architecto adipisci, animi, saepe ipsam dignissimos id.\n Perspiciatis quisquam odio consectetur quaerat? Nam fuga, ex quam reprehenderit corporis in similique repellendus repudiandae consectetur incidunt culpa, magnam qui vero, quaerat atque laborum suscipit animi ipsa praesentium. Mollitia, a.\n Commodi similique a laboriosam, expedita enim numquam quos sit at tempora ullam ad possimus itaque, sint, eius quod minus explicabo dolores! Quidem minus esse facere dolorem, voluptate dignissimos deleniti minima?\n Numquam, aliquid nostrum possimus nam, eligendi dolor corrupti obcaecati modi eaque illo quas quaerat commodi sint nihil impedit expedita, laudantium non distinctio consectetur repudiandae veniam iste quis! Saepe, quaerat aliquam.\n Hic, laborum! Voluptas delectus autem quas inventore neque enim rem suscipit voluptatum earum tenetur repellat quidem, officia nesciunt quasi, ut unde architecto. Quae ea veniam soluta suscipit sed quo accusamus?\n Odit, modi! Expedita ipsam, rerum suscipit quibusdam eos, dolorem nihil fugit sequi, voluptatem exercitationem earum. Vitae dolorem a illo earum, eum, sed labore et tempore odit consequatur ipsa optio reprehenderit.\n Eius, sed alias perferendis, cupiditate laudantium, officia ab incidunt eaque error aperiam accusamus rerum et vero fuga suscipit cum molestiae est aut odio. Ea cum assumenda ullam fugiat, dolores et.\n Sit deserunt voluptate alias nobis dolore aperiam placeat neque error! Magni et maxime earum, hic numquam beatae necessitatibus deserunt. Quae repellendus consequuntur cumque voluptates reiciendis quos explicabo ea, officiis cupiditate!\n Totam, assumenda ut ea cupiditate, esse delectus commodi, laboriosam soluta sed nesciunt distinctio recusandae provident expedita voluptas ab natus consectetur voluptatibus. Praesentium commodi nemo error hic corporis illo voluptatibus modi.\n",
    "points": "100",
    "available_date": "2025-09-01T00:00:00",
    "due_date": "2025-09-11T23:59:00"
  }
]
